;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;==========================================================

[colors]
background = #101010
background-alt = #ff0000
foreground = #ffffff

primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #8b8b8b
color01 = #FFC799

[bar/example]
width = 100%
height = 24pt
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-top-size = 4pt
border-left-size = 4pt
border-right-size = 4pt
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = BlexMono Nerd Font:size-10;2

modules-left = xworkspaces xwindow
modules-right = filesystem pulseaudio xkeyboard memory cpu wlan eth date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-foreground = ${colors.foreground}
label-active-underline = ${colors.color01}
label-active-padding = 1


label-occupied = %name%
label-occupied-foreground = ${colors.disabled}
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %class%

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.foreground}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted =  muted
label-muted-foreground = ${colors.disabled}

[module/date]
type = internal/date
interval = 1

date = %d-%m-%Y %H:%M

label = %date%
label-foreground = ${colors.foreground}

[settings]
screenchange-reload = true
pseudo-transparency = true
